{{- if $.Values.security.admin.autogenerateSecret.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "eventstore.fullname" . }}-password-generator
spec:
  length: 18
  digits: 6
  symbols: 5
  symbolCharacters: "~!@#$%^&*()_+-={}|[]:<>?,./"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "eventstore.fullname" . }}-admin-password
spec:
  refreshInterval: "0"
  target:
    name: {{ include "eventstore.fullname" . }}-admin-password
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "eventstore.fullname" . }}-password-generator
{{ end }}
