apiVersion: v1  
kind: Service  
metadata:  
  name: {{ include "eventstore.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    helm.sh/chart: {{ include "eventstore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
spec:  
  selector:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http2-port
      protocol: TCP
      port: {{ .Values.extHttpPort }}
      targetPort: {{ .Values.extHttpPort }}
  {{- if (.Values.external.enabled) }}
  type: ExternalName
  externalName: "{{ include "eventstore.fullname" . }}.{{ .Values.external.name }}.svc.cluster.local"
  {{- else }}
  clusterIP: None
  {{- end }}
