apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eventstore.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    reloader.stakater.com/search: "true"
  labels:
    app.kubernetes.io/name: {{ include "eventstore.name" . }}
    helm.sh/chart: {{ include "eventstore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eventstore.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.clusterSize }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "eventstore.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/eventstore-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "eventstore.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: database
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:      
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsUser: 0
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if $.Values.security.admin.passwordSecretRef.name }}
          env:
            - name: EVENTSTORE_DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.security.admin.passwordSecretRef.name | quote }}
                  key: {{ $.Values.security.admin.passwordSecretRef.key | quote }}
          {{- else if $.Values.security.admin.autogenerateSecret.enabled }}
          env:
            - name: EVENTSTORE_DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eventstore.fullname" . }}-admin-password
                  key: password
            - name: EVENTSTORE_DEFAULT_OPS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eventstore.fullname" . }}-admin-password
                  key: password
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "eventstore.fullname" . }}-env
          ports:
            - containerPort: {{ .Values.intTcpPort }}
            - containerPort: {{ .Values.extHttpPort }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.extHttpPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.extHttpPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
            - name: index
              mountPath: {{ .Values.persistence.index.mountPath }}
            {{- if .Values.security.certificates.autogenerate.enabled }}
            - name: certificates
              mountPath: /etc/ssl/certs
            {{- end }}
      volumes:
      {{- if (not .Values.persistence.enabled) }}
        - name: data
          emptyDir: {}
        - name: index
          emptyDir: {}
      {{- end }}
      {{- if .Values.security.certificates.autogenerate.enabled }}
        - name: certificates
          projected:
            sources:
              - secret:
                  name: {{ include "eventstore.fullname" . }}-node
                  items:
                    - key: ca.crt
                      path: node.ca.crt
                    - key: tls.crt
                      path: node.tls.crt
                    - key: tls.key
                      path: node.tls.key
              - secret:
                  name: {{ include "eventstore.fullname" . }}-client-root
                  items:
                    - key: ca.crt
                      path: client.ca.crt
                    - key: tls.crt
                      path: client.tls.crt
                    - key: tls.key
                      path: client.tls.key
      {{- end }}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    {{ with .Values.persistence.data }}
    - metadata:
        name: data
        namespace: {{ $.Release.Namespace | quote }}
        labels:
          app.kubernetes.io/name: {{ include "eventstore.name" $ }}
      {{- with .annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
          - {{ .accessMode | quote }}
        resources:
          requests:
            storage: {{ .size | quote }}
      {{- if .storageClass }}
      {{- if (eq "-" .storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .storageClass }}"
      {{- end }}
      {{- end }}
      {{- end }}

    {{ with .Values.persistence.index }}
    - metadata:
        name: index
        namespace: {{ $.Release.Namespace | quote }}
        labels:
          app.kubernetes.io/name: {{ include "eventstore.name" $ }}
      {{- with .annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
          - {{ .accessMode | quote }}
        resources:
          requests:
            storage: {{ .size | quote }}
      {{- if .storageClass }}
      {{- if (eq "-" .storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .storageClass }}"
      {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
